// Synthetic end-to-end acceptance. Run by CI against the built browser package.
const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {spawn,execFileSync}=require('node:child_process');
(async()=>{
 const output=fs.mkdtempSync('/tmp/options-flow-');
 const server=spawn('python3',['-u','-m','http.server','0','--bind','127.0.0.1','--directory',path.resolve('out')]);
 let browser;
 try{
  const url=await new Promise((resolve,reject)=>{const t=setTimeout(()=>reject(Error('Server timeout')),10000);server.stdout.on('data',d=>{const m=String(d).match(/http:\/\/127\.0\.0\.1:\d+/);if(m){clearTimeout(t);resolve(m[0]);}});server.on('error',reject);});
  browser=await chromium.launch({headless:true});
  const page=await browser.newPage({viewport:{width:1440,height:1000},acceptDownloads:true});page.setDefaultTimeout(90000);
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto(url);
  assert.equal(await page.locator('html').getAttribute('lang'),'en');
  assert.doesNotMatch(await page.locator('body').innerText(), /\p{Script=Han}/u);
  await page.getByRole('button',{name:'Try an example',exact:true}).click();
  await page.locator('#results').waitFor({state:'visible'});
  assert.equal(await page.locator('#value').innerText(),'571.52');
  assert.equal(await page.locator('#greek-rows tr').count(),5);
  await page.getByRole('combobox',{name:'Example',exact:true}).selectOption('counterexample');
  await page.getByRole('button',{name:'Try an example',exact:true}).click();
  await page.locator('#results').waitFor({state:'visible'});
  assert.match(await page.locator('#approx-note').innerText(),/295.00.*-487.35.*782.35/);
  async function save(selector,name){const pending=page.waitForEvent('download');await page.locator(selector).click();const d=await pending;const file=path.join(output,name);await d.saveAs(file);assert.equal(await d.failure(),null);return file;}
  const file=await save('#download-json','counterexample.json');
  const report=await save('#download-html','report.html');
  const exported=JSON.parse(fs.readFileSync(file));
  const py="import json,sys; from options_risk.scenarios import analyse; q=json.load(open(sys.argv[1])); print(json.dumps(analyse(q['request'])))";
  const expected=JSON.parse(execFileSync('python3',['-c',py,file],{encoding:'utf8'}));
  let numeric=0;
  function parity(a,b){if(typeof a==='number'){assert(Math.abs(a-b)<=1e-10+1e-8*Math.abs(b));numeric++;}else if(a&&typeof a==='object'){assert.deepEqual(Object.keys(a),Object.keys(b));Object.keys(a).forEach(k=>parity(a[k],b[k]));}else assert.equal(a,b);}
  parity(exported.result,expected);
  const html=fs.readFileSync(report,'utf8');assert.doesNotMatch(html,/\p{Script=Han}/u);assert.match(html,/Annual vol/);assert.match(html,/1.0000%/);assert.match(html,/currency per 1 vol percentage point/);assert.match(html,/not VaR/);
  const reportPage=await browser.newPage();await reportPage.goto('file://'+report);assert(await reportPage.getByRole('heading',{name:'Portfolio sensitivities'}).isVisible());await reportPage.close();
  await page.getByRole('spinbutton',{name:'Spot price',exact:true}).fill('101');assert(await page.locator('#results').isHidden());assert.equal(await page.locator('#download-json').getAttribute('href'),null);assert.match(await page.locator('#case-note').innerText(),/changed/);
  await page.getByRole('button',{name:'Enter your positions',exact:true}).click();assert.equal(await page.locator('[name=spot]').inputValue(),'');assert.equal(await page.locator('#positions tbody tr').count(),1);
  const bad=path.join(output,'bad.json');fs.writeFileSync(bad,'{"positions":[]}');await page.locator('#file').setInputFiles(bad);await page.locator('#error').waitFor({state:'visible'});assert.doesNotMatch(await page.locator('#error').innerText(),/\p{Script=Han}/u);
  // Imported file is generated separately from the UI fixture.
  const custom={...exported.request,underlying:'CUSTOM_SYNTHETIC',spot:100,positions:[{id:'external-call',kind:'call',style:'european',strike:100,expiry:'2026-10-29',quantity:2,multiplier:100,volatility:.2}],scenarios:[{name:'unchanged',days:0,spot_return:0,vol_change:0},{name:'up 1%',days:0,spot_return:.01,vol_change:0}]};
  const customPath=path.join(output,'custom.json');fs.writeFileSync(customPath,JSON.stringify(custom));await page.locator('#file').setInputFiles(customPath);await page.waitForFunction(()=>document.querySelector('#case-note').textContent.includes('imported'));assert.match(await page.locator('#case-note').innerText(),/Custom/);assert(await page.locator('#error').isHidden());
  await page.getByRole('button',{name:'Calculate portfolio',exact:true}).click();await page.locator('#results').waitFor({state:'visible'});const customExport=await save('#download-json','custom-result.json');const c=JSON.parse(fs.readFileSync(customExport));parity(c.result,JSON.parse(execFileSync('python3',['-c',py,customExport],{encoding:'utf8'})));
  await page.screenshot({path:path.join(output,'desktop.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:path.join(output,'mobile.png'),fullPage:true});

  // Quote review is a complete file -> diagnostics -> selected portfolio task.
  await page.setViewportSize({width:1440,height:1000});
  await page.goto(url+'/quotes.html');
  await page.getByRole('button',{name:'Try quote example',exact:true}).click();
  await page.getByRole('button',{name:'Cancel calculation',exact:true}).click();
  assert(await page.locator('#quote-inputs').isEnabled());
  assert(await page.locator('#quote-results').isHidden());
  await page.getByRole('button',{name:'Check quotes',exact:true}).click();
  await page.locator('#quote-results').waitFor({state:'visible'});
  assert.match(await page.locator('#quote-summary').innerText(),/2 quote rows; 0 need review/);
  assert.equal(await page.locator('#quote-selection input[type=checkbox]:checked').count(),0);
  const quoteJSON=await save('#quote-json','quotes.json');
  const quoteHTML=await save('#quote-html','quotes.html');
  const quoteExport=JSON.parse(fs.readFileSync(quoteJSON));
  const quotePy="import json,sys; from options_risk.quotes import review_quotes; q=json.load(open(sys.argv[1])); print(json.dumps(review_quotes(q['request'])))";
  parity(quoteExport,JSON.parse(execFileSync('python3',['-c',quotePy,quoteJSON],{encoding:'utf8'})));
  assert.match(fs.readFileSync(quoteHTML,'utf8'),/American midpoint step sensitivity/);
  await page.getByLabel('Quote bid',{exact:true}).first().fill('10.6');
  assert(await page.locator('#quote-results').isHidden());
  assert.equal(await page.locator('#quote-json').getAttribute('href'),null);
  // Import a file with a good row and a crossed quote, then repair the bad row.
  const external={...quoteExport.request,quotes:[{...quoteExport.request.quotes[0],id:'custom-long'}, {...quoteExport.request.quotes[0],id:'custom-short',bid:12,ask:10}]};
  const externalFile=path.join(output,'quotes-external.json');fs.writeFileSync(externalFile,JSON.stringify(external));
  await page.locator('#quote-file').setInputFiles(externalFile);
  await page.getByRole('button',{name:'Check quotes',exact:true}).click();
  await page.locator('#quote-results').waitFor({state:'visible'});
  assert.match(await page.locator('#quote-summary').innerText(),/1 need review/);
  assert(!(await page.getByLabel('Use custom-short',{exact:true}).isEnabled()));
  await page.getByLabel('Quote bid',{exact:true}).nth(1).fill('10.7');
  await page.getByLabel('Quote ask',{exact:true}).nth(1).fill('10.9');
  await page.getByRole('button',{name:'Check quotes',exact:true}).click();
  await page.locator('#quote-results').waitFor({state:'visible'});
  await page.getByLabel('Use custom-short',{exact:true}).check();
  await page.getByRole('button',{name:'Open selected positions in scenarios',exact:true}).click();
  assert.match(await page.locator('#quote-transfer-status').innerText(),/quantity/);
  await page.getByLabel('Quantity custom-short',{exact:true}).fill('-2');
  await page.getByLabel('Multiplier custom-short',{exact:true}).fill('0.5');
  await page.getByRole('button',{name:'Open selected positions in scenarios',exact:true}).click();
  assert.match(await page.locator('#quote-transfer-status').innerText(),/integer multiplier/);
  await page.getByLabel('Multiplier custom-short',{exact:true}).fill('100');
  await page.getByLabel('IV source custom-short',{exact:true}).selectOption('mid');
  const expectedIV=quoteExport.rows[0].estimates.mid.volatility;
  const selectedJSON=await save('#quote-portfolio','selected-portfolio.json');
  const selected=JSON.parse(fs.readFileSync(selectedJSON));
  assert.equal(selected.request.positions[0].quantity,-2);assert.equal(selected.request.positions[0].multiplier,100);
  assert(Math.abs(selected.request.positions[0].volatility-expectedIV)<1e-10);
  await page.setViewportSize({width:390,height:844});
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.screenshot({path:path.join(output,'quotes-mobile.png'),fullPage:true});
  await page.getByRole('button',{name:'Open selected positions in scenarios',exact:true}).click();
  await page.waitForURL(url+'/index.html');
  assert.equal(await page.evaluate(()=>sessionStorage.getItem('options-risk-quote-transfer-v1')),null);
  assert.equal(await page.locator('#positions tbody tr').count(),1);
  assert.equal(await page.getByLabel('Position quantity',{exact:true}).inputValue(),'-2');
  assert(Math.abs(Number(await page.getByLabel('Annual volatility percent',{exact:true}).inputValue())-expectedIV*100)<1e-9);
  assert.match(await page.locator('#case-note').innerText(),/Volatility imported from quote review/);
  await page.getByRole('button',{name:'Add scenario',exact:true}).click();
  await page.getByLabel('Scenario name',{exact:true}).nth(1).fill('Spot rises 2%');
  await page.getByLabel('Spot change percent',{exact:true}).nth(1).fill('2');
  await page.getByRole('button',{name:'Calculate portfolio',exact:true}).click();
  await page.locator('#results').waitFor({state:'visible'});
  const transferredFile=await save('#download-json','quote-portfolio-result.json');
  const transferredHTML=await save('#download-html','quote-portfolio-report.html');
  const transferred=JSON.parse(fs.readFileSync(transferredFile));
  parity(transferred.result,JSON.parse(execFileSync('python3',['-c',py,transferredFile],{encoding:'utf8'})));
  assert(transferred.result.scenarios[1].pnl<0);
  assert.match(fs.readFileSync(transferredHTML,'utf8'),/Volatility imported from quote review/);
  await page.locator('#file').setInputFiles(bad);await page.locator('#error').waitFor({state:'visible'});
  assert(await page.locator('#results').isHidden());assert.equal(await page.locator('#download-html').getAttribute('href'),null);
  // Transfer is consumed once, never replayed on refresh; corruption is explicit.
  await page.reload();assert.equal(await page.locator('[name=underlying]').inputValue(),'SYNTHETIC_ETF');
  await page.evaluate(()=>sessionStorage.setItem('options-risk-quote-transfer-v1','broken'));
  await page.reload();assert.match(await page.locator('#error').innerText(),/Quote transfer failed/);
  assert.equal(await page.evaluate(()=>sessionStorage.getItem('options-risk-quote-transfer-v1')),null);
  await page.locator('#file').setInputFiles(selectedJSON);assert(await page.locator('#error').isHidden());
  assert.equal(await page.getByLabel('Multiplier',{exact:true}).inputValue(),'100');
  await page.getByRole('button',{name:'Calculate portfolio',exact:true}).click();await page.locator('#results').waitFor({state:'visible'});
  const roundtripHTML=await save('#download-html','roundtrip-source.html');assert.match(fs.readFileSync(roundtripHTML,'utf8'),/Volatility imported from quote review/);
  const badTypes={...transferred.request,spot:true};
  const wrongTypePath=path.join(output,'wrong-type.json');fs.writeFileSync(wrongTypePath,JSON.stringify(badTypes));
  await page.locator('#file').setInputFiles(wrongTypePath);assert.match(await page.locator('#error').innerText(),/finite number/);
  await page.goto(url+'/quotes.html');
  await page.locator('#quote-file').setInputFiles(bad);await page.locator('#quote-error').waitFor({state:'visible'});
  await page.locator('#quote-file').setInputFiles(quoteJSON);
  assert(await page.locator('#quote-error').isHidden());
  assert.match(await page.locator('#quote-note').innerText(),/imported/);
  assert.doesNotMatch(await page.locator('body').innerText(),/\p{Script=Han}/u);
  assert.deepEqual(errors,[]);fs.writeFileSync(path.join(output,'validation.json'),JSON.stringify({numeric_fields_compared:numeric,quote_review:true,quote_transfer:true,quote_cancel_recovery:true,quote_report_parity:true,consumed_transfer:true,strict_numeric_import:true,example:true,counterexample:true,custom_import:true,invalid_recovery:true,report_saved_and_read:true,stale_export_revoked:true,desktop:true,mobile:true,errors},null,2));
  fs.mkdirSync('outputs',{recursive:true});fs.cpSync(output,'outputs/browser-flow',{recursive:true});console.log('Browser flow passed:',numeric,'numeric fields');
 }finally{if(browser)await browser.close();server.kill();}
})().catch(e=>{console.error(e);process.exitCode=1});
