'use strict';
const $=s=>document.querySelector(s), form=$('#form'), inputset=$('#inputs');
const example={as_of:'2026-09-29',underlying:'SYNTHETIC_ETF',currency:'USD',spot:100,rate:.03,dividend_yield:.01,positions:[{id:'long-call',kind:'call',style:'american',strike:100,expiry:'2026-10-29',quantity:1,multiplier:100,volatility:.25},{id:'long-put',kind:'put',style:'american',strike:100,expiry:'2026-10-29',quantity:1,multiplier:100,volatility:.25}],scenarios:[{name:'Unchanged',spot_return:0,vol_change:0,days:0},{name:'Spot -5%, volatility +5 points',spot_return:-.05,vol_change:.05,days:1},{name:'Spot +5%, unchanged volatility',spot_return:.05,vol_change:0,days:1},{name:'7 calendar days elapsed',spot_return:0,vol_change:0,days:7}]};
const counterexample=structuredClone(example);
counterexample.spot=99;counterexample.rate=0;counterexample.dividend_yield=0;
counterexample.positions.forEach(p=>{p.style='european';p.volatility=.01});
counterexample.scenarios=[{name:'Unchanged',spot_return:0,vol_change:0,days:0},{name:'Small rise: 0.1%',spot_return:.001,vol_change:0,days:0},{name:'Large rise: 5%',spot_return:.05,vol_change:0,days:0}];
function selectedExample(){return $('#case-choice').value==='counterexample'?counterexample:example}
function loadExample(){load(selectedExample());$('#own-note').hidden=true;$('#case-note').textContent=$('#case-choice').value==='counterexample'?'Invented counterexample: at low volatility, spot crosses the strike. Initial Greeks cannot capture this large shock accurately. Compare residuals for small and large shocks.':'A long call and put share the same strike. Explore the effects of spot, volatility and time.';}
let exportURLs=[];
let sourceNote='';
let worker=null,timer=null,serial=0,last=null,busy=false;
const esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function field(key,value,label,type='number',extra=''){return `<input data-key="${key}" aria-label="${label}" type="${type}" value="${esc(value)}" required ${type==='number'?'step="any"':''} ${extra}>`}
function select(key,value,label,values){return `<select data-key="${key}" aria-label="${label}">${values.map(([v,t])=>`<option value="${v}" ${v===value?'selected':''}>${t}</option>`).join('')}</select>`}
function addPosition(p){if($('#positions tbody').children.length>=10)throw Error('Up to 10 positions are supported');const row=document.createElement('tr');row.innerHTML=[field('id',p.id,'Position ID','text','maxlength="80"'),select('kind',p.kind,'Option type',[['call','Call'],['put','Put']]),select('style',p.style,'Exercise style',[['american','American'],['european','European']]),field('strike',p.strike,'Strike','number','min="0.01"'),field('expiry',p.expiry,'Expiry','date'),field('quantity',p.quantity,'Position quantity'),field('multiplier',p.multiplier,'Multiplier','number','min="1"'),field('volatility',p.volatility*100,'Annual volatility percent','number','min="0"')].map(x=>`<td>${x}</td>`).join('')+'<td><button type="button" class="remove" aria-label="Remove position">Remove</button></td>';$('#positions tbody').append(row)}
function addScenario(s){if($('#scenarios tbody').children.length>=10)throw Error('Up to 10 scenarios are supported');const row=document.createElement('tr');row.innerHTML=[field('name',s.name,'Scenario name','text','maxlength="120"'),field('spot_return',(s.spot_return||0)*100,'Spot change percent','number','min="-99.99"'),field('vol_change',(s.vol_change||0)*100,'Volatility change in points'),field('days',s.days||0,'Elapsed calendar days','number','min="0"')].map(x=>`<td>${x}</td>`).join('')+'<td><button type="button" class="remove" aria-label="Remove scenario">Remove</button></td>';$('#scenarios tbody').append(row)}
function invalidate(){exportURLs.forEach(URL.revokeObjectURL);exportURLs=[];['#download-json','#download-html'].forEach(id=>$(id).removeAttribute('href'));last=null;$('#results').hidden=true;$('#status').textContent='Inputs changed. Recalculate to update results.'}
function load(q){sourceNote='';['underlying','currency','as_of','spot','rate','dividend_yield'].forEach(k=>{form.elements[k].value=(k==='rate'||k==='dividend_yield')?(q[k]??0)*100:q[k]});$('#positions tbody').replaceChildren();$('#scenarios tbody').replaceChildren();q.positions.forEach(addPosition);q.scenarios.forEach(addScenario);invalidate();$('#error').hidden=true}
function read(){const q={};['underlying','currency','as_of'].forEach(k=>q[k]=form.elements[k].value);['spot','rate','dividend_yield'].forEach(k=>q[k]=Number(form.elements[k].value)/(k==='spot'?1:100));q.positions=[...$('#positions tbody').children].map(row=>{const p={};row.querySelectorAll('[data-key]').forEach(e=>p[e.dataset.key]=e.type==='number'?Number(e.value):e.value);p.volatility/=100;return p});q.scenarios=[...$('#scenarios tbody').children].map(row=>{const s={};row.querySelectorAll('[data-key]').forEach(e=>s[e.dataset.key]=e.type==='number'?Number(e.value):e.value);s.spot_return/=100;s.vol_change/=100;return s});return q}
function error(e){
 let message=String(e.message||e).replace(/^ValueError:\s*/,'');
 const messages=[
 ['CRR probability outside [0, 1]; change inputs or increase steps','These volatility, rate or maturity inputs are outside the supported range of the 300-step American tree. Check the inputs. No European-model fallback is applied.'],
 ['scenario beyond expiry requires an exercise/settlement ledger; not supported','The scenario extends beyond this position’s expiry. Reduce elapsed days. Post-expiry settlement cash flows are unsupported.'],
 ['years and volatility must be non-negative','Remaining maturity or scenario volatility is negative. Check expiry and volatility changes.'],
 ['quantity times multiplier must be a finite number','Quantity times multiplier exceeds the numeric range. Check quantities and units.'],
 ['portfolio calculation exceeds numeric range; reduce position or scenario magnitude','Portfolio or scenario values exceed the numeric range. Check quantities, multipliers and market changes.'],
 ['positions must expire after the valuation date','Expiry must follow the valuation date.'],
 ['quantity must be a nonzero signed integer','Quantity must be a nonzero integer: positive for long, negative for short.'],
 ['position ids must be nonempty and unique','Each position requires a unique, nonempty ID.'],
 ['scenario names must be nonempty and unique','Each scenario requires a unique, nonempty name.'],
 ['days must be a nonnegative integer','Elapsed days must be a nonnegative integer.']];
 for(const [source,target] of messages)message=message.replace(source,target);
 message=message.replace(/^Position /,'Position ').replace(/^Scenario /,'Scenario ').replace(', position ', ', Position ').replace('(Greeks)', ' (Sensitivities)').replace('(valuation)', ' (Valuation)');
 $('#error').textContent=message;$('#error').hidden=false;
}
function setBusy(v){busy=v;inputset.disabled=v;$('#run').disabled=v;$('#cancel').hidden=!v}
function stop(message){serial++;if(worker)worker.terminate();worker=null;clearTimeout(timer);setBusy(false);invalidate();$('#status').textContent=message}
function money(x){return new Intl.NumberFormat('en-US',{minimumFractionDigits:2,maximumFractionDigits:2}).format(x)}
function render(r){
 const greekRows=[['Delta','delta','First-order portfolio value change per one-unit spot increase'],['Gamma','gamma','Delta change per one-unit spot increase'],['Vega','vega_per_vol_point','Value change per one percentage-point rise in annual volatility'],['Theta','theta_per_day','Value change per calendar day elapsed'],['Rho','rho_per_rate_point','Value change per one percentage-point rise in annual rate']];
 $('#greek-rows').innerHTML=greekRows.map(([name,key,meaning])=>`<tr><td>${name}</td><td>${r.greeks[key].toLocaleString('en-US',{maximumSignificantDigits:6})}</td><td>${esc(meaning)} (${esc(r.currency)}${key==='gamma'?' / spot unit²':key==='delta'?' / spot unit':''})</td></tr>`).join('');
 const largest=r.scenarios.reduce((a,s)=>Math.abs(s.positions.reduce((v,p)=>v+p.approximation_residual,0))>Math.abs(a.positions.reduce((v,p)=>v+p.approximation_residual,0))?s:a,r.scenarios[0]);
 const local=largest.positions.reduce((v,p)=>v+p.greek_approximation,0);
 $('#approx-note').textContent=`Among the listed scenarios, ${largest.name} has the largest absolute approximation residual: full revaluation ${money(largest.pnl)}, local approximation ${money(local)}, difference ${money(largest.pnl-local)} ${r.currency}. This is a difference between calculation methods, not an achievable trading return.`;
$('#value').textContent=money(r.market_value);$('#worst').textContent=money(Math.max(0,-Math.min(...r.scenarios.map(s=>s.pnl))));$('#unit').textContent=r.currency;$('#result-rows').innerHTML=r.scenarios.map(s=>{const approx=s.positions.reduce((a,p)=>a+p.greek_approximation,0);return `<tr><td>${esc(s.name)}</td><td>${esc(s.date)}</td><td class="${s.pnl<0?'negative':'positive'}">${money(s.pnl)}</td><td>${money(approx)}</td><td>${money(s.pnl-approx)}</td></tr>`}).join('');$('#details').innerHTML=r.scenarios.map(s=>`<details><summary>${esc(s.name)}</summary><div class="scroll"><table><thead><tr><th>Position</th><th>Strike</th><th>Expiry</th><th>Model value</th><th>P&L</th><th>Approximation residual</th></tr></thead><tbody>${s.positions.map(p=>`<tr><td>${esc(p.id)}</td><td>${money(p.strike)}</td><td>${esc(p.expiry)}</td><td>${money(p.market_value)}</td><td>${money(p.pnl)}</td><td>${money(p.approximation_residual)}</td></tr>`).join('')}</tbody></table></div></details>`).join('');$('#results').hidden=false}
form.addEventListener('submit',e=>{e.preventDefault();if(busy||!form.reportValidity())return;const request=read();invalidate();$('#error').hidden=true;setBusy(true);$('#status').textContent='Preparing calculation…';const id=++serial;try{worker ||= new Worker('worker.mjs',{type:'module'});worker.onmessage=({data})=>{if(data.id!==serial)return;if(data.progress){$('#status').textContent=data.progress;return}clearTimeout(timer);setBusy(false);if(data.error){error(data.error);$('#status').textContent='No results generated. Check inputs and retry.';return}last={request,result:data.result,html:data.html,source_note:sourceNote};render(data.result);prepareDownloads();$('#results').scrollIntoView({behavior:'smooth',block:'start'});$('#status').textContent='Calculation complete. Results match the inputs above.';};worker.onerror=()=>{stop('Components failed to load. Try again.');error('Calculation components could not start. Check your connection or refresh.')};timer=setTimeout(()=>{stop('Calculation timed out. Reduce positions or scenarios and retry.')},120000);worker.postMessage({id,request,source_note:sourceNote})}catch(e){stop('Unable to start calculation.');error(e)}});
function edited(e){if(!e.target.closest('#scenarios')&&e.target.id!=='case-choice')sourceNote='';invalidate();if(e.target.id!=='case-choice'){$('#case-note').textContent='Inputs have changed. Recalculate; the original example explanation no longer describes this portfolio.';$('#own-note').hidden=true}}
inputset.addEventListener('input',edited);inputset.addEventListener('change',edited);inputset.addEventListener('click',e=>{if(e.target.classList.contains('remove')){if(e.target.closest('#positions'))sourceNote='';e.target.closest('tr').remove();invalidate()}});$('#cancel').onclick=()=>stop('Cancelled. You can edit inputs and retry.');$('#reset').onclick=loadExample;
$('#case-choice').onchange=loadExample;
$('#try-example').onclick=()=>{loadExample();form.requestSubmit()};
$('#own-position').onclick=()=>{load(example);$('#positions tbody').replaceChildren();addPosition({...example.positions[0],id:'position-1'});['underlying','currency','as_of','spot','rate','dividend_yield'].forEach(k=>form.elements[k].value='');$('#positions tbody').querySelectorAll('input').forEach(e=>{if(e.dataset.key!=='id')e.value=''});$('#scenarios tbody').replaceChildren();addScenario({name:'Unchanged',spot_return:0,vol_change:0,days:0});$('#case-note').textContent='Custom portfolio: you supply all inputs. The model does not read live market data.';$('#own-note').hidden=false;form.elements.underlying.focus();};
$('#add-position').onclick=()=>{sourceNote='';try{addPosition({...example.positions[0],id:'position-'+(Date.now()%100000)});invalidate()}catch(e){error(e)}};$('#add-scenario').onclick=()=>{try{addScenario({name:'New scenario',spot_return:0,vol_change:0,days:0});invalidate()}catch(e){error(e)}};
$('#import').onclick=()=>$('#file').click();
$('#file').onchange=async e=>{
 const f=e.target.files[0];if(!f)return;
 const id=++serial;invalidate();$('#error').hidden=true;setBusy(true);$('#status').textContent='Reading selected portfolio JSON…';
 try{if(f.size>1024*1024)throw Error('JSON file limit: 1 MiB');
  const raw=await f.text();if(id!==serial)return;
  const payload=JSON.parse(raw),q=payload.request||payload;validateImport(q);load(q);
  sourceNote=typeof payload.source_note==='string'?payload.source_note.slice(0,4000):'';
  $('#own-note').hidden=true;$('#case-note').textContent='Custom portfolio imported. Check inputs before calculating.';
  $('#status').textContent='Portfolio imported. Ready to calculate.';
 }catch(e){if(id===serial){error(e);$('#status').textContent='Import failed; previous inputs remain, but old results are cleared.';}}
 finally{if(id===serial)setBusy(false);$('#file').value=''}
};
function keys(o,allowed,required){if(!o||typeof o!=='object'||Array.isArray(o)||Object.keys(o).some(k=>!allowed.includes(k))||required.some(k=>!(k in o)))throw Error('File fields do not match the input schema. Download example results as a template.')}
function validateImport(q){keys(q,['underlying','currency','as_of','spot','rate','dividend_yield','positions','scenarios'],['underlying','currency','as_of','spot','positions','scenarios']);if(!Array.isArray(q.positions)||!q.positions.length||q.positions.length>10||!Array.isArray(q.scenarios)||!q.scenarios.length||q.scenarios.length>10)throw Error('Provide 1–10 positions and 1–10 scenarios');q.positions.forEach(p=>{const k=['id','kind','style','strike','expiry','quantity','multiplier','volatility'];keys(p,k,k);if(!['call','put'].includes(p.kind)||!['american','european'].includes(p.style))throw Error('Unsupported option type or exercise style')});q.scenarios.forEach(s=>keys(s,['name','spot_return','vol_change','days'],['name']));validateNumbers(q)}
function validateNumbers(q){
 for(const k of ['underlying','currency','as_of'])if(typeof q[k]!=='string'||!q[k].trim())throw Error(k+' must be nonempty text');
 if(!/^\d{4}-\d{2}-\d{2}$/.test(q.as_of))throw Error('Use an ISO valuation date');
 const number=(o,k)=>{if(typeof o[k]!=='number'||!Number.isFinite(o[k]))throw Error(k+' must be a finite number, not text or a boolean')};
 for(const k of ['spot','rate','dividend_yield'])if(k in q)number(q,k);
 for(const p of q.positions){if(typeof p.id!=='string'||!p.id.trim()||typeof p.expiry!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(p.expiry))throw Error('Check position ID and ISO expiry');for(const k of ['strike','quantity','multiplier','volatility'])number(p,k);if(!Number.isSafeInteger(p.quantity)||p.quantity===0||p.strike<=0||!Number.isSafeInteger(p.multiplier)||p.multiplier<=0||p.volatility<0)throw Error('Check positive strike, positive integer multiplier, nonnegative volatility and nonzero integer quantity');}
 for(const s of q.scenarios){if(typeof s.name!=='string'||!s.name.trim())throw Error('Scenario name must be nonempty text');for(const k of ['spot_return','vol_change','days'])if(k in s)number(s,k);if('days' in s&&(!Number.isSafeInteger(s.days)||s.days<0))throw Error('Elapsed days must be a nonnegative integer');}
}

function prepareDownloads(){
 const payloads=[[JSON.stringify({request:last.request,result:last.result,source_note:last.source_note},null,2),'application/json','#download-json'],[last.html,'text/html','#download-html']];
 payloads.forEach(([content,type,id])=>{const url=URL.createObjectURL(new Blob([content],{type}));exportURLs.push(url);$(id).href=url});
}
window.addEventListener('pagehide',()=>{if(busy)stop('Calculation interrupted. Retry when ready.');else if(worker){worker.terminate();worker=null}});load(example);$('#status').textContent='Example ready. Calculate to view results.';

if(document.modelContext?.registerTool){const lifecycle=new AbortController();try{Promise.resolve(document.modelContext.registerTool({name:'read_option_risk_summary',title:'Read current option risk summary',description:'Read only the completed visible analysis summary; does not start a calculation or change positions.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input){if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw Error('This action accepts an empty object only.');return {calculating:busy,hasCurrentResult:!!last,summary:last?{currency:last.result.currency,modelValue:last.result.market_value,scenarios:last.result.scenarios.map(s=>({name:s.name,pnl:s.pnl}))}:null}}},{signal:lifecycle.signal})).catch(()=>{});}catch(_){}window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}

try {
 const raw=sessionStorage.getItem('options-risk-quote-transfer-v1');
 if(raw!==null){sessionStorage.removeItem('options-risk-quote-transfer-v1');const payload=JSON.parse(raw);validateImport(payload.request);load(payload.request);sourceNote=typeof payload.source_note==='string'?payload.source_note.slice(0,4000):'';$('#case-note').textContent=sourceNote||'Quote-derived positions imported. Review inputs and calculate.';$('#status').textContent='Selected positions imported. Add scenarios and calculate; no risk results have been generated.';}
} catch(e){error('Quote transfer failed: '+String(e.message||e));$('#case-note').textContent='Quote transfer failed. The displayed example is not your selected quote portfolio.';$('#status').textContent='Return to quote review or import the downloaded portfolio.';}
