'use strict';
const $=s=>document.querySelector(s), form=$('#form'), inputset=$('#inputs');
const example={as_of:'2026-09-29',underlying:'SYNTHETIC_ETF',currency:'USD',spot:100,rate:.03,dividend_yield:.01,positions:[{id:'long-call',kind:'call',style:'american',strike:100,expiry:'2026-10-29',quantity:1,multiplier:100,volatility:.25},{id:'long-put',kind:'put',style:'american',strike:100,expiry:'2026-10-29',quantity:1,multiplier:100,volatility:.25}],scenarios:[{name:'不变',spot_return:0,vol_change:0,days:0},{name:'下跌 5%，波动率 +5 点',spot_return:-.05,vol_change:.05,days:1},{name:'上涨 5%，波动率不变',spot_return:.05,vol_change:0,days:1},{name:'经过 7 个自然日',spot_return:0,vol_change:0,days:7}]};
let worker=null,timer=null,serial=0,last=null,busy=false;
const esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function field(key,value,label,type='number',extra=''){return `<input data-key="${key}" aria-label="${label}" type="${type}" value="${esc(value)}" required ${type==='number'?'step="any"':''} ${extra}>`}
function select(key,value,label,values){return `<select data-key="${key}" aria-label="${label}">${values.map(([v,t])=>`<option value="${v}" ${v===value?'selected':''}>${t}</option>`).join('')}</select>`}
function addPosition(p){if($('#positions tbody').children.length>=10)throw Error('最多支持 10 个持仓');const row=document.createElement('tr');row.innerHTML=[field('id',p.id,'持仓编号','text','maxlength="80"'),select('kind',p.kind,'期权类型',[['call','看涨'],['put','看跌']]),select('style',p.style,'行权方式',[['american','美式'],['european','欧式']]),field('strike',p.strike,'执行价','number','min="0.01"'),field('expiry',p.expiry,'到期日','date'),field('quantity',p.quantity,'持仓数量'),field('multiplier',p.multiplier,'合约乘数','number','min="1"'),field('volatility',p.volatility*100,'年化波动率百分比','number','min="0"')].map(x=>`<td>${x}</td>`).join('')+'<td><button type="button" class="remove" aria-label="删除持仓">删除</button></td>';$('#positions tbody').append(row)}
function addScenario(s){if($('#scenarios tbody').children.length>=10)throw Error('最多支持 10 个情景');const row=document.createElement('tr');row.innerHTML=[field('name',s.name,'情景名称','text','maxlength="120"'),field('spot_return',(s.spot_return||0)*100,'标的价格变化百分比','number','min="-99.99"'),field('vol_change',(s.vol_change||0)*100,'波动率变化点数'),field('days',s.days||0,'经过自然日','number','min="0"')].map(x=>`<td>${x}</td>`).join('')+'<td><button type="button" class="remove" aria-label="删除情景">删除</button></td>';$('#scenarios tbody').append(row)}
function invalidate(){last=null;$('#results').hidden=true;$('#status').textContent='输入已更新，请重新计算。'}
function load(q){['underlying','currency','as_of','spot','rate','dividend_yield'].forEach(k=>{form.elements[k].value=(k==='rate'||k==='dividend_yield')?(q[k]??0)*100:q[k]});$('#positions tbody').replaceChildren();$('#scenarios tbody').replaceChildren();q.positions.forEach(addPosition);q.scenarios.forEach(addScenario);invalidate();$('#error').hidden=true}
function read(){const q={};['underlying','currency','as_of'].forEach(k=>q[k]=form.elements[k].value);['spot','rate','dividend_yield'].forEach(k=>q[k]=Number(form.elements[k].value)/(k==='spot'?1:100));q.positions=[...$('#positions tbody').children].map(row=>{const p={};row.querySelectorAll('[data-key]').forEach(e=>p[e.dataset.key]=e.type==='number'?Number(e.value):e.value);p.volatility/=100;return p});q.scenarios=[...$('#scenarios tbody').children].map(row=>{const s={};row.querySelectorAll('[data-key]').forEach(e=>s[e.dataset.key]=e.type==='number'?Number(e.value):e.value);s.spot_return/=100;s.vol_change/=100;return s});return q}
function error(e){$('#error').textContent=String(e.message||e).replace(/^ValueError:\s*/,'');$('#error').hidden=false}
function setBusy(v){busy=v;inputset.disabled=v;$('#run').disabled=v;$('#cancel').hidden=!v}
function stop(message){if(worker)worker.terminate();worker=null;clearTimeout(timer);setBusy(false);invalidate();$('#status').textContent=message}
function money(x){return new Intl.NumberFormat('en-US',{minimumFractionDigits:2,maximumFractionDigits:2}).format(x)}
function render(r){$('#value').textContent=money(r.market_value);$('#worst').textContent=money(Math.max(0,-Math.min(...r.scenarios.map(s=>s.pnl))));$('#unit').textContent=r.currency;$('#result-rows').innerHTML=r.scenarios.map(s=>{const approx=s.positions.reduce((a,p)=>a+p.greek_approximation,0);return `<tr><td>${esc(s.name)}</td><td>${esc(s.date)}</td><td class="${s.pnl<0?'negative':'positive'}">${money(s.pnl)}</td><td>${money(approx)}</td><td>${money(s.pnl-approx)}</td></tr>`}).join('');$('#details').innerHTML=r.scenarios.map(s=>`<details><summary>${esc(s.name)}</summary><div class="scroll"><table><thead><tr><th>持仓</th><th>执行价</th><th>到期日</th><th>模型价值</th><th>损益</th><th>近似误差</th></tr></thead><tbody>${s.positions.map(p=>`<tr><td>${esc(p.id)}</td><td>${money(p.strike)}</td><td>${esc(p.expiry)}</td><td>${money(p.market_value)}</td><td>${money(p.pnl)}</td><td>${money(p.approximation_residual)}</td></tr>`).join('')}</tbody></table></div></details>`).join('');$('#results').hidden=false}
form.addEventListener('submit',e=>{e.preventDefault();if(busy||!form.reportValidity())return;const request=read();invalidate();$('#error').hidden=true;setBusy(true);$('#status').textContent='正在准备计算…';const id=++serial;try{worker ||= new Worker('worker.mjs',{type:'module'});worker.onmessage=({data})=>{if(data.progress){$('#status').textContent=data.progress;return}if(data.id!==serial)return;clearTimeout(timer);setBusy(false);if(data.error){error(data.error);$('#status').textContent='未生成结果。请检查输入后重试。';return}last={request,result:data.result,html:data.html};render(data.result);$('#results').scrollIntoView({behavior:'smooth',block:'start'});$('#status').textContent='计算完成。当前结果对应上方输入。';};worker.onerror=()=>{stop('组件加载失败，可重新计算。');error('计算组件未能运行，请检查网络或刷新后重试。')};timer=setTimeout(()=>{stop('本次计算已超时，请减少持仓或情景后重试。')},120000);worker.postMessage({id,request})}catch(e){stop('无法启动计算。');error(e)}});
inputset.addEventListener('input',invalidate);inputset.addEventListener('change',invalidate);inputset.addEventListener('click',e=>{if(e.target.classList.contains('remove')){e.target.closest('tr').remove();invalidate()}});$('#cancel').onclick=()=>stop('已取消，可以修改输入后重试。');$('#reset').onclick=()=>load(example);
$('#add-position').onclick=()=>{try{addPosition({...example.positions[0],id:'position-'+(Date.now()%100000)});invalidate()}catch(e){error(e)}};$('#add-scenario').onclick=()=>{try{addScenario({name:'新情景',spot_return:0,vol_change:0,days:0});invalidate()}catch(e){error(e)}};
$('#import').onclick=()=>$('#file').click();$('#file').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>1024*1024)throw Error('JSON 文件上限 1 MiB');let q=JSON.parse(await f.text());q=q.request||q;validateImport(q);load(q)}catch(e){error(e)}finally{$('#file').value=''}};
function keys(o,allowed,required){if(!o||typeof o!=='object'||Array.isArray(o)||Object.keys(o).some(k=>!allowed.includes(k))||required.some(k=>!(k in o)))throw Error('文件字段不符合输入格式，请先下载示例结果作为模板。')}
function validateImport(q){keys(q,['underlying','currency','as_of','spot','rate','dividend_yield','positions','scenarios'],['underlying','currency','as_of','spot','positions','scenarios']);if(!Array.isArray(q.positions)||!q.positions.length||q.positions.length>10||!Array.isArray(q.scenarios)||!q.scenarios.length||q.scenarios.length>10)throw Error('需提供 1–10 个持仓及情景');q.positions.forEach(p=>{const k=['id','kind','style','strike','expiry','quantity','multiplier','volatility'];keys(p,k,k);if(!['call','put'].includes(p.kind)||!['american','european'].includes(p.style))throw Error('不支持的期权类型或行权方式')});q.scenarios.forEach(s=>keys(s,['name','spot_return','vol_change','days'],['name']))}
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
$('#download-json').onclick=()=>{if(last)download(new Blob([JSON.stringify({request:last.request,result:last.result},null,2)],{type:'application/json'}),'option-risk-result.json')};$('#download-html').onclick=()=>{if(last)download(new Blob([last.html],{type:'text/html'}),'option-risk-report.html')};window.addEventListener('pagehide',()=>{if(worker)worker.terminate()});load(example);$('#status').textContent='示例已就绪。点击计算查看结果。';

if(document.modelContext?.registerTool){const lifecycle=new AbortController();try{Promise.resolve(document.modelContext.registerTool({name:'read_option_risk_summary',title:'读取当前期权风险摘要',description:'Read only the completed visible analysis summary; does not start a calculation or change positions.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input){if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw Error('This action accepts an empty object only.');return {calculating:busy,hasCurrentResult:!!last,summary:last?{currency:last.result.currency,modelValue:last.result.market_value,scenarios:last.result.scenarios.map(s=>({name:s.name,pnl:s.pnl}))}:null}}},{signal:lifecycle.signal})).catch(()=>{});}catch(_){}window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
