'use strict';
const $=s=>document.querySelector(s), form=$('#quote-form'), inputs=$('#quote-inputs');
const transferKey='options-risk-quote-transfer-v1';
const example={as_of:'2026-01-01',underlying:'INVENTED_ETF',currency:'USD',spot:100,rate:.03,dividend_yield:.01,quotes:[{id:'european-call',kind:'call',style:'european',strike:100,expiry:'2027-01-01',bid:10.7,ask:10.9},{id:'american-put',kind:'put',style:'american',strike:100,expiry:'2027-01-01',bid:9,ask:9.2}]};
let worker=null,timer=null,serial=0,busy=false,last=null,urls=[];
const esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const statusText={solved:'Solved',boundary_at_price_tolerance:'Boundary price — positive IV unresolved',unidentified_at_expiry:'Expired — IV unavailable',inconsistent_expiry_price:'Price differs from expiry payoff',below_model_lower_bound:'Below model lower bound',above_model_upper_bound:'Above model upper bound',unresolved_at_asymptotic_bound:'At upper price bound',unresolved_at_tree_floor:'Outside resolved tree domain',empty_search_domain:'No admissible search range',above_search_cap:'Above 500% search cap',unresolved_at_search_cap:'At search cap',not_converged:'Did not converge',low_price_sensitivity:'Weak price sensitivity',negative_price_slope:'Negative price slope'};
function field(key,value,type='number'){return `<input data-key="${key}" aria-label="Quote ${key}" type="${type}" value="${esc(value)}" required ${type==='number'?'step="any"':''}>`}
function choice(key,value,options){return `<select data-key="${key}" aria-label="Quote ${key}">${options.map(v=>`<option value="${v}" ${v===value?'selected':''}>${v}</option>`).join('')}</select>`}
function add(q){if($('#quote-table tbody').children.length>=10)throw Error('Up to 10 quotes are supported in the browser.');const tr=document.createElement('tr');tr.innerHTML=[field('id',q.id,'text'),choice('kind',q.kind,['call','put']),choice('style',q.style,['european','american']),field('strike',q.strike),field('expiry',q.expiry,'date'),field('bid',q.bid),field('ask',q.ask)].map(v=>`<td>${v}</td>`).join('')+'<td><button type="button" class="quote-remove">Remove</button></td>';$('#quote-table tbody').append(tr)}
function fail(e){$('#quote-error').textContent=String(e.message||e).replace(/^ValueError:\s*/,'');$('#quote-error').hidden=false}
function invalidate(){last=null;urls.forEach(URL.revokeObjectURL);urls=[];$('#quote-results').hidden=true;$('#quote-selection').replaceChildren();for(const id of ['#quote-json','#quote-html'])$(id).removeAttribute('href');$('#quote-transfer-status').textContent='';$('#quote-status').textContent='Inputs changed. Check quotes again.'}
function setBusy(value){busy=value;inputs.disabled=value;$('#quote-run').disabled=value;$('#quote-cancel').hidden=!value}
function stop(message){serial++;if(worker)worker.terminate();worker=null;clearTimeout(timer);setBusy(false);invalidate();$('#quote-status').textContent=message}
function load(q){for(const key of ['underlying','currency','as_of','spot','rate','dividend_yield'])form.elements[key].value=(key==='rate'||key==='dividend_yield')?(q[key]??0)*100:q[key];$('#quote-table tbody').replaceChildren();q.quotes.forEach(add);invalidate();$('#quote-error').hidden=true}
function read(){const q={};for(const key of ['underlying','currency','as_of'])q[key]=form.elements[key].value;for(const key of ['spot','rate','dividend_yield'])q[key]=Number(form.elements[key].value)/(key==='spot'?1:100);q.quotes=[...$('#quote-table tbody').children].map(tr=>Object.fromEntries([...tr.querySelectorAll('[data-key]')].map(e=>[e.dataset.key,e.type==='number'?Number(e.value):e.value])));return q}
function shape(o,allowed,required){if(!o||typeof o!=='object'||Array.isArray(o)||Object.keys(o).some(k=>!allowed.includes(k))||required.some(k=>!(k in o)))throw Error('File fields do not match the quote input format. Download example results as a template.')}
function validate(q){shape(q,['underlying','currency','as_of','spot','rate','dividend_yield','quotes'],['underlying','currency','as_of','spot','quotes']);for(const k of ['underlying','currency','as_of'])if(typeof q[k]!=='string'||!q[k].trim())throw Error(k+' must be nonempty text');for(const k of ['spot','rate','dividend_yield'])if(k in q&&(typeof q[k]!=='number'||!Number.isFinite(q[k])))throw Error(k+' must be a finite number');if(!/^\d{4}-\d{2}-\d{2}$/.test(q.as_of))throw Error('Use an ISO valuation date');if(!Array.isArray(q.quotes)||!q.quotes.length||q.quotes.length>10)throw Error('Provide 1–10 quotes');for(const row of q.quotes){const keys=['id','kind','style','strike','expiry','bid','ask'];shape(row,keys,keys);if(typeof row.id!=='string'||typeof row.expiry!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(row.expiry)||!['call','put'].includes(row.kind)||!['european','american'].includes(row.style))throw Error('Check quote ID, type, style and ISO expiry');for(const k of ['strike','bid','ask'])if(typeof row[k]!=='number'||!Number.isFinite(row[k]))throw Error(`Quote ${row.id}: ${k} must be a finite number`);}}
function estimateText(e){if(!e)return 'Unavailable';const label=statusText[e.status]||e.status;return e.volatility===null?label:`${(e.volatility*100).toFixed(5)}% · ${label}`}
function render(r){$('#quote-summary').textContent=`${r.rows.length} quote rows; ${r.attention_count} need review.`;$('#quote-values').innerHTML=r.rows.map(row=>`<tr><td>${esc(row.input.id||'Row '+row.row)}</td>${['bid','mid','ask'].map(k=>`<td>${esc(estimateText(row.estimates?.[k]))}</td>`).join('')}<td>${row.estimates?.mid?.residual==null?'Unavailable':esc(row.estimates.mid.residual.toExponential(3))}</td><td>${esc(row.error||(row.status==='solved'?'Model inversion solved':'Inspect endpoint statuses'))}</td></tr>`).join('');$('#quote-steps').innerHTML=r.rows.filter(row=>row.mid_step_diagnostics).map(row=>`<details class="method"><summary>${esc(row.input.id)}: American midpoint step sensitivity</summary><p>300-step IV: ${esc(estimateText(row.estimates.mid))}. Alternative fixed trees:</p><ul>${row.mid_step_diagnostics.map(e=>`<li>${e.steps} steps: ${esc(estimateText(e))}; price residual ${esc(e.residual)}</li>`).join('')}</ul><p>These changes reflect tree discretisation; solver convergence does not establish model convergence.</p></details>`).join('');$('#quote-selection').innerHTML=r.rows.map((row,i)=>{const usable=['bid','mid','ask'].filter(k=>row.estimates?.[k]?.status==='solved');return `<tr data-row="${i}"><td><input type="checkbox" aria-label="Use ${esc(row.input.id)}" ${usable.length?'':'disabled'}></td><td>${esc(row.input.id||'Row '+row.row)}</td><td><select aria-label="IV source ${esc(row.input.id)}" ${usable.length?'':'disabled'}>${usable.length?usable.map(k=>`<option value="${k}" ${k==='mid'?'selected':''}>${k} · ${(row.estimates[k].volatility*100).toFixed(5)}%</option>`).join(''):'<option>No solved estimate</option>'}</select></td><td><input data-position="quantity" type="number" step="1" aria-label="Quantity ${esc(row.input.id)}" placeholder="e.g. -1"></td><td><input data-position="multiplier" type="number" step="1" min="1" aria-label="Multiplier ${esc(row.input.id)}" placeholder="e.g. 100"></td></tr>`}).join('');$('#quote-results').hidden=false;}
function downloads(){for(const [id,type,content] of [['#quote-json','application/json',JSON.stringify(last.result,null,2)],['#quote-html','text/html',last.html]]){const url=URL.createObjectURL(new Blob([content],{type}));urls.push(url);$(id).href=url}}
form.addEventListener('submit',event=>{event.preventDefault();if(busy||!form.reportValidity())return;const request=read();invalidate();$('#quote-error').hidden=true;setBusy(true);const id=++serial;try{worker ||= new Worker('worker.mjs',{type:'module'});worker.onmessage=({data})=>{if(data.id!==undefined&&data.id!==serial)return;if(data.progress){$('#quote-status').textContent=data.progress;return}clearTimeout(timer);setBusy(false);if(data.error){fail(data.error);$('#quote-status').textContent='Check the input and retry.';return}last={request,result:data.result,html:data.html};render(data.result);downloads();$('#quote-status').textContent='Quote check complete. Review every endpoint before using an estimate.';};worker.onerror=()=>{stop('Calculation components failed. Retry or refresh.');fail('Unable to start local calculation components.')};timer=setTimeout(()=>stop('Timed out. Use fewer American quotes and retry.'),120000);worker.postMessage({id,action:'quotes',request})}catch(e){stop('Unable to start quote check.');fail(e)}});
inputs.addEventListener('input',invalidate);inputs.addEventListener('change',invalidate);inputs.addEventListener('click',e=>{if(e.target.classList.contains('quote-remove')){e.target.closest('tr').remove();invalidate()}});
$('#quote-example').onclick=()=>{load(example);$('#quote-note').textContent='Invented example: European call and American put.';form.requestSubmit()};
$('#quote-own').onclick=()=>{load(example);$('#quote-table tbody').replaceChildren();add({...example.quotes[0],id:'quote-1',strike:'',expiry:'',bid:'',ask:''});for(const e of form.querySelectorAll('.market input'))e.value='';$('#quote-note').textContent='Custom quotes: supply matching valuation inputs and contract prices.';form.elements.underlying.focus()};
$('#quote-add').onclick=()=>{try{add({...example.quotes[0],id:'quote-'+Date.now(),strike:'',expiry:'',bid:'',ask:''});invalidate()}catch(e){fail(e)}};
$('#quote-cancel').onclick=()=>stop('Cancelled. Edit inputs or retry.');$('#quote-import').onclick=()=>$('#quote-file').click();
$('#quote-file').onchange=async event=>{
 const file=event.target.files[0];if(!file)return;
 const id=++serial;invalidate();$('#quote-error').hidden=true;setBusy(true);$('#quote-status').textContent='Reading selected quote JSON…';
 try{if(file.size>1024*1024)throw Error('JSON file limit: 1 MiB');
  const raw=await file.text();if(id!==serial)return;let q=JSON.parse(raw);q=q.request||q;validate(q);load(q);
  $('#quote-note').textContent='Custom quotes imported. Check inputs before calculating.';$('#quote-status').textContent='Quotes imported. Ready to check.';
 }catch(e){if(id===serial){fail(e);$('#quote-status').textContent='Import failed; previous inputs remain, but old results are cleared.';}}
 finally{if(id===serial)setBusy(false);$('#quote-file').value=''}
};
function selectedPortfolio(){if(!last)throw Error('Check quotes before selecting estimates.');const positions=[],sources=[];for(const tr of $('#quote-selection').children){if(!tr.querySelector('input[type=checkbox]').checked)continue;const row=last.result.rows[Number(tr.dataset.row)],label=tr.querySelector('select').value,estimate=row.estimates?.[label];if(estimate?.status!=='solved')throw Error('Only a solved endpoint can be transferred');const quantity=Number(tr.querySelector('[data-position=quantity]').value),multiplier=Number(tr.querySelector('[data-position=multiplier]').value);if(!Number.isSafeInteger(quantity)||quantity===0||!Number.isSafeInteger(multiplier)||multiplier<=0)throw Error(`Enter a nonzero integer quantity and positive integer multiplier for ${row.input.id}`);const {id,kind,style,strike,expiry}=row.input;positions.push({id,kind,style,strike,expiry,quantity,multiplier,volatility:estimate.volatility});sources.push(`${id}: ${label} premium ${estimate.premium}, ${estimate.model}${estimate.steps?' '+estimate.steps+' steps':''}`)}if(!positions.length)throw Error('Select at least one solved estimate');const {as_of,underlying,currency,spot,rate,dividend_yield}=last.request;return {request:{as_of,underlying,currency,spot,rate,dividend_yield,positions,scenarios:[{name:'Unchanged',days:0,spot_return:0,vol_change:0}]},source_note:'Volatility imported from quote review; conditional model estimates. '+sources.join('; ')+'. Keep the separate quote report for inputs, endpoint warnings and numerical sensitivity.'}}
$('#quote-transfer').onclick=()=>{try{const payload=selectedPortfolio();sessionStorage.setItem(transferKey,JSON.stringify(payload));location.href='index.html'}catch(e){$('#quote-transfer-status').textContent=String(e.message||e)}};
$('#quote-portfolio').onclick=()=>{try{const payload=selectedPortfolio();const url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));urls.push(url);const a=document.createElement('a');a.href=url;a.download='quote-derived-portfolio.json';a.click();$('#quote-transfer-status').textContent='Portfolio downloaded. Import it in Portfolio scenarios and review before calculating.'}catch(e){$('#quote-transfer-status').textContent=String(e.message||e)}};
window.addEventListener('pagehide',()=>{if(busy)stop('Calculation interrupted. Retry when ready.');else if(worker){worker.terminate();worker=null}});load(example);$('#quote-status').textContent='Example ready.';
